### PR TITLE
Use foreman_config_entry instead of manual rake config

### PR DESCRIPTION
**Pull request by ekohl**
I should note that I haven't tested this yet, this is mostly to check if this is even a good idea. https://github.com/theforeman/puppet-foreman/issues/441 also suggested that this should be part of puppet-foreman itself.

### CODE REVIEW

**Comment by ekohl** [comment]
https://github.com/theforeman/puppet-foreman/pull/442 is an alternative approach. Using that would mean simply setting the correct answers.

**Comment by ehelms** [comment]
I can test this out with our module-pr tester in kdeploy. As for the parameters, I'd still probably learn towards this approach given we'd have to define the certs in the answers file of the installer and then they are hard-coded as opposed to this approach that will update them if anything changes.

**Comment by ekohl** [comment]
The current certificate locations are already hardcoded in the katello-installer answers file. By implementing this, you reduce coupling which I think is a good thing.

**Comment by stbenjam** [comment]
Closed in favor of https://github.com/Katello/puppet-certs/pull/88

**Pull request closed without merging**
