### PR TITLE
Fixes #15700 - make sure change of certs propagates changes in nssdb

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by mbacovsky** [comment]
ACK, the patch fixed the issue with qpid certs. 
The reproducing scenario didn't finish okay though and failed on another cert bug. (@iNecas is going to report it).

**Comment by iNecas** [comment]
Additional issue with certs, similar as this one, but in yet another storage https://bugzilla.redhat.com/show_bug.cgi?id=1357028

**Comment by iNecas** [comment]
@ehelms I've not been mergning to this repo for a while. Or for me to do it or you want?

**Comment by ehelms** [comment]
Been meaning to, sorry for delay!

**Pull request merged**
