### PR TITLE
Fixes #16911 - cert-req should not require

### PR DESCRIPTION
**Pull request by ahumbe**
foreman-installer should not require --certs-server-cert-req parameter

### CODE REVIEW

**Comment by ekohl** [comment]
I don't know the details of it, but removing it sounds like more than just 'not require'.

**Comment by ahumbe** [comment]
The REQ file is passed by the CA server to sign it so I think foreman has no use of req file.  In case of using custom ssl certs signed by thirdpary CA it should not be a required parameter for installer to pass. Please correct me if any thing missing/wrong.

**Comment by ehelms** [comment]
Since we do not currently sign the custom certificates with the default CA, this is a sound change. The bigger question should be whether we should be signing the custom certificates or not with two questions in mind:

 1) would it simplify deployment (currently we pass around two CA crts everywhere)
 2) would it couple the certificates too much

**Comment by ahumbe** [comment]
@ehelms Hi, did you get chance to review this ?

**Comment by ekohl** [comment]
I'm still a bit unfamiliar with the whole certs module and @ehelms is afk for a while. I do wonder why you left the parameter in for foreman_proxy.

**Comment by ekohl** [comment]
There are conflicts now and I'm not sure how to proceed with this.

**Comment by tbrisker** [comment]
@ekohl @ahumbe @ehelms Any chance you can try moving this issue forward?

**Comment by ekohl** [comment]
Closing in favor of #172

**Pull request closed without merging**
