### PR TITLE
Refs #8372 - generate client certificates to be used by the smart proxy

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by iNecas** [comment]
@ehelms @stbenjam anyone willing to look at this

**Comment by ehelms** [comment]
@iNecas the change this depends on - did that go into Foreman 1.7 or will just be in Foreman 1.8?

**Comment by iNecas** [comment]
Not yet, but it's a blocker bug https://bugzilla.redhat.com/show_bug.cgi?id=1180051 as it blocks the abrt and openscap integration, we would need to backport this to foreman 1.7 or cherrypick in katello-installer //cc @dcleal

**Comment by ehelms** [comment]
ACK - if the Foreman change gets backported to 1.7, we can backport for 2.1 otherwise it will just have to go out in 2.2.

**Comment by stbenjam** [comment]
@iNecas Can you merge ASAP? I need this for the some capsule isolation things.

**Pull request merged**
