### PR TITLE
Fixes #10097 - Fixed references to city

### PR DESCRIPTION
**Pull request by adamruzicka**
In many places it was referenced as 'sity'

### CODE REVIEW

**Comment by stbenjam** [comment]
Looks like we need to update katello-devel module as well:
 `puppet-katello_devel/manifests/foreman_certs.pp: :    city          => $::certs::sity`

**Comment by adamruzicka** [comment]
I'll check all the katello's repositories for more appearances of it tomorrow

**Comment by stbenjam** [comment]
That's the only reference I saw in katello-installer, but anyway, I'll ack whatever PR's come out of this together so we don't do break anything.

**Comment by stbenjam** [comment]
ACK

**Comment by ehelms** [comment]
@stbenjam please go ahead and merge this

**Pull request merged**
