### PR TITLE
fixes #15882 - support AIO paths for puppet

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by beav** [comment]
testing this now

**Comment by stbenjam** [comment]
This makes the ENC work, so `puppet agent --test` works on the Katello

**Comment by beav** [comment]
APJ, works for me. I will remove the hack this clears from https://github.com/Katello/forklift/pull/260 once merged.

**Comment by ekohl** [comment]
For non-AIO installs this changes the location from ```/etc/puppet``` to (the default) ```/var/lib/puppet/ssl```. Will this break existing installs on upgrades?

**Comment by stbenjam** [comment]
> For non-AIO installs this changes the location from /etc/puppet to (the default) /var/lib/puppet/ssl. Will this break existing installs on upgrades?

/etc/puppet/ssl is just a symlink to /var/lib/puppet/ssl, but I can leave it how we have it now, it was mostly just because I copied foreman's code for this

**Comment by stbenjam** [comment]
Oh I see what you mean, katello was putting the certs into just /etc/puppet.  Not sure that makes sense, they should go to the ssl dir.

**Comment by ekohl** [comment]
I'm fine with the code as is it now, just concerned about upgrading users. Sounds like a major version bump with a note in the release notes (and maybe katello-installer needs to migrate the certs for upgrading users).

**Comment by stbenjam** [comment]
There shouldn't be an upgrade issue, the installer will fix it.  We keep generated certs in /root/ssl-build and deploy them to these paths that puppet tells us, and anyone using the paths references the $::certs variables.

**Comment by ekohl** [comment]
ACK then

**Comment by stbenjam** [comment]
Thanks!

**Pull request merged**
